### ISSUE TITLE
ClassNotFoundException while running the standalone

### ISSUE THREAD

**Issue by Chris336** [itplr-kosit/validator-configuration-xrechnung#21]
After following the steps as written in the README file and running the follwoing command in CMD:
`C:\XRechnung>java -jar validationtool-1.0.1-standalone.jar -s scenarios.xml -h 01.01a-INVOICE_ubl.xml`
I'm receiving a ClassNotFound Exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at de.kosit.validationtool.impl.DefaultCheck.<init>(DefaultCheck.java:73)
        at de.kosit.validationtool.cmd.InternalCheck.<init>(InternalCheck.java:48)
        at de.kosit.validationtool.cmd.CommandLineApplication.processActions(CommandLineApplication.java:135)
        at de.kosit.validationtool.cmd.CommandLineApplication.mainProgram(CommandLineApplication.java:105)
        at de.kosit.validationtool.cmd.CommandLineApplication.main(CommandLineApplication.java:85)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```
Is there something I missed?

Best regards.

**Comment by phax** [comment]
Are you eventually running Java 9+?
in that case try adding
```xml
        <dependency>
          <groupId>org.glassfish.jaxb</groupId>
          <artifactId>jaxb-runtime</artifactId>
          <version>2.3.2</version>
        </dependency>
```
